blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/libratuslounge
    about: Get help from the community
  - name: Documentation
    url: https://github.com/AlabamaMike/LibratusLounge/tree/main/docs
    about: Check our documentation for answers
  - name: Security Issue
    url: mailto:security@libratuslounge.com
    about: Please report security vulnerabilities via email
