name = "primo-poker-server"
main = "dist/index.js"
compatibility_date = "2024-01-17"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-super-secret-jwt-key-for-development-only-change-in-production"
ALLOWED_ORIGINS = "https://localhost:3000"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "primo-poker-db"
database_id = "c112bb87-1024-4bf1-b698-193913831358"
migrations_dir = "./migrations"

# KV Namespace for sessions
[[kv_namespaces]]
binding = "SESSION_STORE"
id = "6ef4c203e65f429082df51bbec8bb19e"
preview_id = "d7b0477a22d94639806c8533d46682a9"

# R2 Bucket for hand history
[[r2_buckets]]
binding = "HAND_HISTORY_BUCKET"
bucket_name = "primo-poker-hand-history"
preview_bucket_name = "primo-poker-hand-history-preview"

# R2 Bucket for RNG audit logs
# TODO: Create this R2 bucket before uncommenting
# [[r2_buckets]]
# binding = "AUDIT_BUCKET"
# bucket_name = "primo-poker-rng-audit"
# preview_bucket_name = "primo-poker-rng-audit-preview"

# Durable Objects
[[durable_objects.bindings]]
name = "TABLE_OBJECTS"
class_name = "TableDurableObject"
script_name = "primo-poker-server"

# New GameTable Durable Object for multiplayer games
[[durable_objects.bindings]]
name = "GAME_TABLES"
class_name = "GameTableDurableObject"
script_name = "primo-poker-server"

# Same DO with different binding name for permission checks
[[durable_objects.bindings]]
name = "GAME_TABLE_DO"
class_name = "GameTableDurableObject"
script_name = "primo-poker-server"

# Secure RNG Durable Object
[[durable_objects.bindings]]
name = "SECURE_RNG_DO"
class_name = "SecureRNGDurableObject"
script_name = "primo-poker-server"

# Rate Limiting Durable Object
[[durable_objects.bindings]]
name = "RATE_LIMIT_DO"
class_name = "RateLimitDurableObject"
script_name = "primo-poker-server"

[[migrations]]
tag = "v1"
new_classes = ["TableDurableObject"]

[[migrations]]
tag = "v2"
new_classes = ["GameTableDurableObject"]

[[migrations]]
tag = "v3"
new_classes = ["SecureRNGDurableObject", "RateLimitDurableObject"]

# Queue for tournament processing
[[queues.producers]]
queue = "tournament-queue"
binding = "TOURNAMENT_QUEUE"

[[queues.consumers]]
queue = "tournament-queue"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 3
dead_letter_queue = "tournament-dlq"

# Analytics Engine for metrics
[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "primo-poker-metrics"

# Secrets (set via wrangler secret put)
# JWT_SECRET
# DATABASE_ENCRYPTION_KEY
# ANTHROPIC_API_KEY (for AI features)

[build]
command = "npm run build"
cwd = "./"
watch_dir = "src"
