name = "primo-poker-frontend"
compatibility_date = "2024-01-17" 
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

# Environment variables for production
[vars]
NEXT_PUBLIC_API_URL = "https://primo-poker-server.alabamamike.workers.dev"
NEXT_PUBLIC_WS_URL = "wss://primo-poker-server.alabamamike.workers.dev"
NEXT_PUBLIC_ENVIRONMENT = "production"
