name: Test Desktop Build

on:
  pull_request:
    paths:
      - 'apps/poker-desktop/**'
      - '.github/workflows/test-desktop-build.yml'
  workflow_dispatch:

jobs:
  test-build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.platform }}
    
    defaults:
      run:
        working-directory: ./apps/poker-desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Get pnpm store directory (Windows)
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $env:GITHUB_OUTPUT
        id: pnpm-cache-win

      - name: Get pnpm store directory (Unix)
        if: matrix.platform != 'windows-latest'
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT
        id: pnpm-cache-unix

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache-win.outputs.STORE_PATH || steps.pnpm-cache-unix.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        run: |
          cd ../..
          pnpm install --no-frozen-lockfile
          cd apps/poker-desktop

      - name: Lint code
        run: pnpm run lint
        continue-on-error: true

      - name: Run tests
        run: pnpm test
        continue-on-error: true

      - name: Build frontend only
        run: pnpm run build:vite

      - name: Build Tauri app
        run: pnpm run tauri build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: |
            apps/poker-desktop/src-tauri/target/release/bundle/
          retention-days: 7